export interface ApplicationPortalProfile {
  id: string;
  name: string;
  portal: string;
  type: 'photo' | 'signature';
  category: 'gov-exam' | 'passport-visa' | 'banking' | 'admissions';
  width: number;
  height: number;
  minKb?: number;
  maxKb: number;
  format: 'image/jpeg' | 'image/png';
  backgroundColor: string; // hex
  backgroundName: string;
  aspectRatio: string;
  aspectRatioNumber: number;
  officialRuleText: string;
}

export const APPLICATION_PORTALS: ApplicationPortalProfile[] = [
  // --- Indian Government & Exam Portals ---
  {
    id: 'ssc-cgl-photo',
    name: 'SSC CGL / CHSL Photo',
    portal: 'Staff Selection Commission (SSC)',
    type: 'photo',
    category: 'gov-exam',
    width: 350,
    height: 450,
    minKb: 20,
    maxKb: 50,
    format: 'image/jpeg',
    backgroundColor: '#FFFFFF',
    backgroundName: 'Pure White',
    aspectRatio: '7:9 (3.5 × 4.5 cm)',
    aspectRatioNumber: 350 / 450,
    officialRuleText: 'Photo size 20KB to 50KB, width 3.5cm, height 4.5cm, strictly light/white plain background.',
  },
  {
    id: 'ssc-cgl-sig',
    name: 'SSC CGL / CHSL Signature',
    portal: 'Staff Selection Commission (SSC)',
    type: 'signature',
    category: 'gov-exam',
    width: 140,
    height: 60,
    minKb: 10,
    maxKb: 20,
    format: 'image/jpeg',
    backgroundColor: '#FFFFFF',
    backgroundName: 'Pure White Paper',
    aspectRatio: '7:3 (4.0 × 2.0 cm)',
    aspectRatioNumber: 140 / 60,
    officialRuleText: 'Signature size 10KB to 20KB, width 4.0cm, height 2.0cm in black ink on white paper.',
  },
  {
    id: 'upsc-civil-photo',
    name: 'UPSC Civil Services Photo',
    portal: 'Union Public Service Commission (UPSC)',
    type: 'photo',
    category: 'gov-exam',
    width: 350,
    height: 350,
    minKb: 20,
    maxKb: 300,
    format: 'image/jpeg',
    backgroundColor: '#FFFFFF',
    backgroundName: 'Plain White',
    aspectRatio: '1:1 Square (min 350×350 px)',
    aspectRatioNumber: 1,
    officialRuleText: 'Pixel resolution between 350×350 and 1000×1000 px, size 20KB to 300KB in JPG.',
  },
  {
    id: 'upsc-civil-sig',
    name: 'UPSC Civil Services Signature',
    portal: 'Union Public Service Commission (UPSC)',
    type: 'signature',
    category: 'gov-exam',
    width: 350,
    height: 150,
    minKb: 20,
    maxKb: 300,
    format: 'image/jpeg',
    backgroundColor: '#FFFFFF',
    backgroundName: 'Plain White',
    aspectRatio: '7:3 (min 350 px width)',
    aspectRatioNumber: 350 / 150,
    officialRuleText: 'Clear scanned signature in black ink on white paper, 20KB to 300KB in JPG.',
  },
  {
    id: 'ibps-bank-photo',
    name: 'IBPS Bank PO / Clerk Photo',
    portal: 'Institute of Banking Personnel Selection',
    type: 'photo',
    category: 'banking',
    width: 200,
    height: 230,
    minKb: 20,
    maxKb: 50,
    format: 'image/jpeg',
    backgroundColor: '#FFFFFF',
    backgroundName: 'Plain White',
    aspectRatio: '20:23',
    aspectRatioNumber: 200 / 230,
    officialRuleText: 'Dimensions 200×230 pixels, file size 20KB to 50KB, white background.',
  },
  {
    id: 'ibps-bank-sig',
    name: 'IBPS Bank Signature',
    portal: 'Institute of Banking Personnel Selection',
    type: 'signature',
    category: 'banking',
    width: 140,
    height: 60,
    minKb: 10,
    maxKb: 20,
    format: 'image/jpeg',
    backgroundColor: '#FFFFFF',
    backgroundName: 'Plain White Paper',
    aspectRatio: '7:3 (140 × 60 px)',
    aspectRatioNumber: 140 / 60,
    officialRuleText: 'Dimensions 140×60 pixels, file size 10KB to 20KB, black ink only.',
  },

  // --- Passports & Visas ---
  {
    id: 'us-visa-ds160',
    name: 'US Visa / DS-160 Photo',
    portal: 'US Department of State Consular Affairs',
    type: 'photo',
    category: 'passport-visa',
    width: 600,
    height: 600,
    maxKb: 240,
    format: 'image/jpeg',
    backgroundColor: '#FFFFFF',
    backgroundName: 'Strict Pure White',
    aspectRatio: '1:1 Square (2 × 2 in)',
    aspectRatioNumber: 1,
    officialRuleText: 'Square 600×600 px (2×2 in), maximum 240KB, plain white or off-white background, neutral expression.',
  },
  {
    id: 'indian-passport-seva',
    name: 'Indian Passport (Passport Seva)',
    portal: 'Ministry of External Affairs (CPV Division)',
    type: 'photo',
    category: 'passport-visa',
    width: 413,
    height: 531,
    minKb: 20,
    maxKb: 100,
    format: 'image/jpeg',
    backgroundColor: '#FFFFFF',
    backgroundName: 'Plain White',
    aspectRatio: '3.5 × 4.5 cm (300 DPI)',
    aspectRatioNumber: 413 / 531,
    officialRuleText: '3.5cm × 4.5cm, 20KB to 100KB, white background, facial coverage 70% to 80%.',
  },
  {
    id: 'schengen-visa-photo',
    name: 'Schengen European Visa',
    portal: 'European Consular Services',
    type: 'photo',
    category: 'passport-visa',
    width: 413,
    height: 531,
    maxKb: 200,
    format: 'image/jpeg',
    backgroundColor: '#E0F2FE',
    backgroundName: 'Light Blue / Light Gray',
    aspectRatio: '3.5 × 4.5 cm',
    aspectRatioNumber: 413 / 531,
    officialRuleText: '35×45mm biometric standard, light gray or light blue background, eye level centered.',
  },
];
