import type { ToolInfo } from '../types';

export const TOOLS: ToolInfo[] = [
  {
    id: 'compress',
    title: 'Compress IMAGE',
    shortDescription: 'Compress image to exact target size in KB or MB with optimal quality.',
    longDescription: 'Reduce image file size to fit strict upload requirements (e.g. max 20KB, 50KB, 100KB) for government forms, job portals, and university applications.',
    iconName: 'Minimize2',
    path: '/compress',
    badge: 'Target KB',
    popular: true,
    colorTheme: 'red',
    group: 'optimize',
  },
  {
    id: 'resize',
    title: 'Resize IMAGE',
    shortDescription: 'Resize by exact pixels, percentage, aspect ratio, or official portal presets.',
    longDescription: 'Adjust image dimensions maintaining perfect aspect ratios or custom pixel presets tailored for passport photos, exam portals, and documents.',
    iconName: 'Maximize2',
    path: '/resize',
    popular: true,
    colorTheme: 'blue',
    group: 'edit',
  },
  {
    id: 'crop',
    title: 'Crop IMAGE',
    shortDescription: 'Crop images by defining rectangle in pixels or using official aspect ratios.',
    longDescription: 'Trim unwanted borders, center face in photo, or frame signatures with precision cropping tools.',
    iconName: 'Crop',
    path: '/crop',
    colorTheme: 'orange',
    group: 'edit',
  },
  {
    id: 'convert',
    title: 'Convert to JPG / PNG',
    shortDescription: 'Convert between JPG, PNG, and WebP formats instantly in browser.',
    longDescription: 'Change image formats seamlessly to meet portal file type restrictions (e.g. converting PNG transparent signatures to JPG with white background).',
    iconName: 'RefreshCw',
    path: '/convert',
    colorTheme: 'green',
    group: 'optimize',
  },
  {
    id: 'signature',
    title: 'Signature Editor',
    shortDescription: 'Clean background shadows, sharpen ink, and recolor scanned signatures.',
    longDescription: 'Isolate signature lineart, convert dark scanned backgrounds to pure white or transparent, and change signature ink to blue, black, or red.',
    iconName: 'PenTool',
    path: '/signature',
    badge: 'Specialized',
    popular: true,
    colorTheme: 'violet',
    group: 'security',
  },
  {
    id: 'batch',
    title: 'Batch Processor & ZIP',
    shortDescription: 'Compress, convert, or resize multiple images at once and export as ZIP.',
    longDescription: 'High-volume batch processor for photos and documents with simultaneous target KB compression, format conversion, and client-side ZIP packaging.',
    iconName: 'Layers',
    path: '/batch',
    badge: 'Multi-File',
    popular: true,
    colorTheme: 'cyan',
    group: 'optimize',
  },
  {
    id: 'metadata',
    title: 'EXIF & Privacy Stripper',
    shortDescription: 'Inspect hidden GPS coordinates and camera specs, and wipe all metadata.',
    longDescription: 'Detect GPS location, device serial numbers, and capture timestamps in your photos and wipe 100% of EXIF chunks for portal privacy.',
    iconName: 'ShieldAlert',
    path: '/metadata',
    badge: 'Privacy',
    popular: true,
    colorTheme: 'rose',
    group: 'security',
  },
  {
    id: 'background',
    title: 'Change Background',
    shortDescription: 'Change photo background to standard white, blue, black, or custom color.',
    longDescription: 'Swap plain passport or application photo backgrounds to meet official requirements (white/blue background guidelines).',
    iconName: 'Palette',
    path: '/background',
    colorTheme: 'fuchsia',
    group: 'edit',
  },
  {
    id: 'editor',
    title: 'Photo Studio Editor',
    shortDescription: 'Combine crop, resize, compress, rotate, brightness, and contrast in one screen.',
    longDescription: 'Comprehensive studio view for multi-step editing before downloading final processed photo.',
    iconName: 'Sliders',
    path: '/editor',
    colorTheme: 'amber',
    group: 'edit',
  },
];
