import type { ToolInfo } from '../types';

export const TOOLS: ToolInfo[] = [
  {
    id: 'compress',
    title: 'Image Compressor',
    shortDescription: 'Compress image to exact target size in KB or MB without quality loss.',
    longDescription: 'Reduce image file size to fit strict upload requirements (e.g. max 20KB, 50KB, 100KB) for government forms, job portals, and university applications.',
    iconName: 'Minimize2',
    path: '/compress',
    badge: 'Target KB',
    popular: true,
  },
  {
    id: 'resize',
    title: 'Image Resizer',
    shortDescription: 'Resize by exact pixels (WxH), aspect ratios, percentages or official presets.',
    longDescription: 'Adjust image dimensions maintaining perfect aspect ratios or custom pixel presets tailored for passport photos, exam portals, and documents.',
    iconName: 'Maximize2',
    path: '/resize',
    popular: true,
  },
  {
    id: 'convert',
    title: 'Format Converter',
    shortDescription: 'Convert between JPG, PNG, and WebP formats instantly in browser.',
    longDescription: 'Change image formats seamlessly to meet portal file type restrictions (e.g. converting PNG transparent signatures to JPG with white background).',
    iconName: 'RefreshCw',
    path: '/convert',
  },
  {
    id: 'signature',
    title: 'Signature Editor',
    shortDescription: 'Enhance scanned signatures, change ink color, and adjust background.',
    longDescription: 'Isolate signature lineart, convert dark scanned backgrounds to pure white or transparent, and change signature ink to blue, black, or red.',
    iconName: 'PenTool',
    path: '/signature',
    badge: 'Specialized',
    popular: true,
  },
  {
    id: 'background',
    title: 'Background Color',
    shortDescription: 'Change photo background to standard white, blue, black, or custom color.',
    longDescription: 'Swap plain passport or application photo backgrounds to meet official requirements (white/blue background guidelines).',
    iconName: 'Palette',
    path: '/background',
  },
  {
    id: 'crop',
    title: 'Image Crop Tool',
    shortDescription: 'Crop photo with freehand, fixed ratio, square, or passport aspect ratios.',
    longDescription: 'Trim unwanted borders, center face in photo, or frame signatures with precision cropping tools.',
    iconName: 'Crop',
    path: '/crop',
  },
  {
    id: 'editor',
    title: 'Full All-in-One Editor',
    shortDescription: 'Combine crop, resize, compress, rotate, brightness, and contrast in one screen.',
    longDescription: 'Comprehensive studio view for multi-step editing before downloading final processed photo.',
    iconName: 'Sliders',
    path: '/editor',
  },
];
